### PR TITLE
Add BuildExt from pycvodes to setup.py

### PR DESCRIPTION
**Pull request by bjodah**
cc @Rolleroo
would you mind trying this branch?

The first error line in your log read:
error C2039: 'exc_type': is not a member of '_ts'

I googled for that and some results mentioned having to use latest version of cython.

### CODE REVIEW

**Comment by Rolleroo** [comment]
@bjodah 

Hi Bjorn,

Downloaded the new fork 0.3.0 and installed from the local copy using "pip install -e C:\<yourfile>.

I've dropped the user output and log into this message. Yeah, seems to have installled! I've included the user and log outputs.

Tried testing it with pytest command but didn't work, not entirely sure why. Is there a way to simply test that it is operating correctly?

My IDE (PyCharm ) hasn't picked up the manually installed module. I assume this is a PyCharm issue rather than your module. I am hoping it appears when I install the module inside PyCharm i.e. it is committed to conda repository?

This is awesome, seems like we are getting there :)

Thanks again,
Kenny

[install.txt](https://github.com/bjodah/batemaneq/files/4267264/install.txt)
[log.txt](https://github.com/bjodah/batemaneq/files/4267276/log.txt)

**Comment by Rolleroo** [comment]
cc @bjodah 
Downloaded the code and installed via pip from a local file which looks to have been successful.

My PyCharm IDE hasn't picked it up. Is there a simple way to test that it is up a

[in
[log.txt](https://github.com/bjodah/batemaneq/files/4267464/log.txt)
stall.txt](https://github.com/bjodah/batemaneq/files/4267254/install.txt)

**Comment by bjodah** [comment]
Glad to hear.

From your log I can see from:
c:\users\callan-daddy\appdata\local\programs\python\python38-32\lib\site-packages\batemaneq.egg-link

That it is using a python environment under:
c:\users\callan-daddy\appdata\local\programs\python\python38-32

So the question is if your PyCharm installation uses another root directory?

The package will need to be installed using pip, in order to make it installable from conda it needs to be built for conda, e.g. on conda-forge. But I'm afraid I won't have the time to maintain that recipe. If you'd still like to see a conda package you would need to add it yourself. It isn't too hard to add it there, their documentation is quite excellent (with that said, one do need to jump through some hoops).

**Comment by bjodah** [comment]
to test the installation it should be possible to run:
python3.8 -m pytest --pyargs batemaneq

**Comment by Rolleroo** [comment]
@bjodah 

Hi Bjorn,

Thanks again for you patience and support. Sorry I didn't realise updating conda would be such an inconvenience. There is no need to do this as I managed to pull the module from GitHub in PyCharm using the PyCharm terminal and command below, which has integrated it into the IDE virtual environment.

pip install git+https://github.com/Rolleroo/batemaneq@tentative-windows-support

The pytest module isn't available, doesn't seem to have come across with the batemaneq module. I get the following error with python. Is this only available in the conda repository?

C:\Users\Callan-Daddy\PycharmProjects\KennysFirstPycharm\venv\Scripts\python.exe: No module named pytest

I ran the "test_bateman.py" in the batemaneq module, is this equivalent to pytest module? It output the value 4.0. Is there a typo in this script as my version has the code below. I am guessing "basteman" is not properly defined?

> 
@pytest.mark.parametrize('p', (0, 1, 2, 3, 4, 5))
**def test_basteman_parent(p):**
    from scipy.special import binom
    from math import 
> 

Again I really appreciate your time and effort. I hope we are nearly there.

All the best,
Kenny AKA @Rolleroo

**Comment by bjodah** [comment]
Thanks, the typo should be unrelated.

Have you installed pytest?

Here's what things look like for me on the terminal:
```
bjorn@urania:/tmp$ python3 -c "import batemaneq" # exits without error                          
bjorn@urania:/tmp$ python3 -c "import pytest" # exits without error                             
bjorn@urania:/tmp$ python3 -m pytest --pyargs batemaneq                                         
/opt/cpython-3.8/lib/python3.8/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
===================================== test session starts ======================================
platform linux -- Python 3.8.1+, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /tmp
plugins: flakes-4.0.0, pep8-1.0.6
collected 9 items                                                                              

tests/test_bateman.py .........                                                          [100%]

====================================== 9 passed in 0.18s =======================================
```

**Comment by Rolleroo** [comment]
@bjodah 

Yes that is what I get, required some extra modules such as scipy but works on the windows command line. Again some issues with my required modules in my IDE but I think I can get that working, seems like lapack isn't bundled with it.

Once again thanks for your expertise on this. I have certainly learned a thing or two trying to get this to work.

Now to put it into practise!

@Rolleroo AKA Kenny

**Comment by bjodah** [comment]
Happy to help!

**Pull request merged**
